version: '3.8'

services:
    dev:
        container_name: nestjs_client
        build:
            context: ./            
            # target: development
            dockerfile: ./Dockerfile
        ports:
            - "3001:3000"
        # environment:
          # HELLO_SERVICE_HOST: '127.0.0.1'
          # HELLO_SERVICE_PORT: 8080
        networks:
            - nestjs-network
        volumes:
            - .src:/usr/app
        restart: unless-stopped
networks:
    nestjs-network: